// Defines API routes for catalog and inventory features.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.catalogRouter = void 0;
const { Router } = require("express");
const { UserRole } = require("@prisma/client");
const { authenticate } = require("../middleware/auth.middleware");
const { requireRole } = require("../middleware/rbac.middleware");
const { validate } = require("../middleware/validate.middleware");
const schemas = require("../schemas/business.schema");
const controller = require("../controllers/catalog.controller");
exports.catalogRouter = Router();
const canWrite = [UserRole.TENANT_ADMIN, UserRole.WAREHOUSE_MANAGER, UserRole.STAFF_MEMBER];
const canAdminStock = [UserRole.TENANT_ADMIN, UserRole.WAREHOUSE_MANAGER];
exports.catalogRouter.use(authenticate);
exports.catalogRouter.get("/locations", controller.listLocations);
exports.catalogRouter.post("/locations", requireRole(...canAdminStock), validate(schemas.createLocationSchema), controller.createLocation);
exports.catalogRouter.get("/locations/:id", validate(schemas.idParamSchema), controller.getLocation);
exports.catalogRouter.patch("/locations/:id", requireRole(...canAdminStock), validate(schemas.updateLocationSchema), controller.updateLocation);
exports.catalogRouter.delete("/locations/:id", requireRole(UserRole.TENANT_ADMIN), validate(schemas.idParamSchema), controller.deleteLocation);
exports.catalogRouter.get("/skus", controller.listSkus);
exports.catalogRouter.post("/skus", requireRole(UserRole.TENANT_ADMIN, UserRole.WAREHOUSE_MANAGER), validate(schemas.createSkuSchema), controller.createSku);
exports.catalogRouter.get("/skus/:id", validate(schemas.idParamSchema), controller.getSku);
exports.catalogRouter.patch("/skus/:id", requireRole(UserRole.TENANT_ADMIN, UserRole.WAREHOUSE_MANAGER), validate(schemas.updateSkuSchema), controller.updateSku);
exports.catalogRouter.delete("/skus/:id", requireRole(UserRole.TENANT_ADMIN), validate(schemas.idParamSchema), controller.deleteSku);
exports.catalogRouter.get("/inventory", controller.listInventory);
exports.catalogRouter.get("/inventory/low-stock", controller.listLowStock);
exports.catalogRouter.get("/inventory/dead-stock", controller.listDeadStock);
exports.catalogRouter.post("/inventory/receive", requireRole(...canWrite), validate(schemas.receiveInventorySchema), controller.receiveInventory);
exports.catalogRouter.get("/inventory/:id", validate(schemas.idParamSchema), controller.getInventory);
exports.catalogRouter.patch("/inventory/:id", requireRole(...canAdminStock), validate(schemas.updateInventorySchema), controller.updateInventory);
